#!/usr/bin/env bash
# VBMF runner toolchain manifest collector (Phase 1, v1.2)
#
# Contract: docs/architecture/CI_RUNNER_STRATEGY.md §6/§9 (D-GATE evidence)
# Writes machine-consumable YAML + human-auditable TXT to
#   /data/actions-runners/vbmf/manifests/<name>/{toolchain.yaml,toolchain.txt}
# Records: timestamp, runner name, hostname, OS, kernel, arch, tool versions
# and absolute paths. NEVER records secrets, tokens or proxy credentials.
#
# Usage (preferably as the runner user):
#   ./collect-toolchain.sh --name vbmf-ci-01 [--base /data/actions-runners/vbmf]
set -euo pipefail

BASE="/data/actions-runners/vbmf"
NAME=""
while [ $# -gt 0 ]; do
  case "$1" in
    --name) NAME="${2:-}"; shift 2 ;;
    --base) BASE="${2:-}"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[ -n "$NAME" ] || { echo "--name is required (e.g. vbmf-ci-01)" >&2; exit 2; }

OUT_DIR="$BASE/manifests/$NAME"
mkdir -p "$OUT_DIR"
STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
HOSTNAME_="$(hostname 2>/dev/null || echo unknown)"
KERNEL="$(uname -r)"
ARCH="$(uname -m)"
OS_PRETTY="$(. /etc/os-release 2>/dev/null && echo "${PRETTY_NAME:-unknown}" || echo unknown)"

# idempotent marker used by both outputs
TOOLS="git python3 rustc cargo cargo-clippy rustdoc clang pkg-config curl"

emit_tool_lines_yaml() {
  local t p v
  for t in $TOOLS; do
    p="$(command -v "$t" 2>/dev/null || true)"
    if [ -n "$p" ]; then
      v="$("$t" --version 2>&1 | head -1)"
      printf '  %s:\n    path: "%s"\n    version: "%s"\n' "$t" "$p" "$v"
    else
      printf '  %s:\n    path: null\n    version: null\n' "$t"
    fi
  done
}
emit_tool_lines_txt() {
  local t p v
  for t in $TOOLS; do
    p="$(command -v "$t" 2>/dev/null || true)"
    if [ -n "$p" ]; then
      v="$("$t" --version 2>&1 | head -1)"
      printf '%-12s %s\n           %s\n' "$t:" "$v" "$p"
    else
      printf '%-12s MISSING\n' "$t:"
    fi
  done
}

# DeckLink SDK host pin (media tier only; general runners record absent).
# Version + header count only — never header contents or payload hashes.
SDK_ROOT="/usr/local/share/decklink-sdk"
emit_sdk_yaml() {
  if [ -d "$SDK_ROOT/include" ] && [ -r "$SDK_ROOT/VERSION" ]; then
    printf 'decklink_sdk:\n  path: "%s"\n  version: "%s"\n  header_count: %s\n' \
      "$SDK_ROOT/include" "$(tr -d '[:space:]' < "$SDK_ROOT/VERSION")" \
      "$(find "$SDK_ROOT/include" -maxdepth 1 -name '*.h' | wc -l)"
  else
    printf 'decklink_sdk:\n  path: null\n  version: "absent"\n  header_count: 0\n'
  fi
}
emit_sdk_txt() {
  if [ -d "$SDK_ROOT/include" ] && [ -r "$SDK_ROOT/VERSION" ]; then
    printf '\ndecklink sdk : %s (%s headers)\n             %s\n' \
      "$(tr -d '[:space:]' < "$SDK_ROOT/VERSION")" \
      "$(find "$SDK_ROOT/include" -maxdepth 1 -name '*.h' | wc -l)" \
      "$SDK_ROOT/include"
  else
    printf '\ndecklink sdk : ABSENT (general tier)\n'
  fi
}

{
  echo "# generated by scripts/ci/collect-toolchain.sh — evidence only, zero secrets"
  echo "runner:"
  echo "  name: \"$NAME\""
  echo "  captured_at: \"$STAMP\""
  echo "  hostname: \"$HOSTNAME_\""
  echo "  os: \"$OS_PRETTY\""
  echo "  kernel: \"$KERNEL\""
  echo "  arch: \"$ARCH\""
  echo "tools:"
  emit_tool_lines_yaml
  emit_sdk_yaml
} > "$OUT_DIR/toolchain.yaml"

{
  echo "VBMF runner toolchain manifest"
  echo "runner name : $NAME"
  echo "captured at : $STAMP (UTC)"
  echo "hostname    : $HOSTNAME_"
  echo "os          : $OS_PRETTY"
  echo "kernel      : $KERNEL"
  echo "arch        : $ARCH"
  echo
  emit_tool_lines_txt
  emit_sdk_txt
} > "$OUT_DIR/toolchain.txt"

echo "wrote $OUT_DIR/toolchain.yaml"
echo "wrote $OUT_DIR/toolchain.txt"
