//! Gate 6/7 — real DeckLink device enumeration via bindgen-generated FFI.
//!
//! With the `decklink` feature compiled in, `bindings.rs` (generated by `build.rs` from
//! `DeckLinkAPI.h`) provides the COM vtable structs. We dlopen `libDeckLinkAPI.so` (the same
//! library validated by Gate 2.5), call `CreateDeckLinkIteratorInstance_0004` to obtain an
//! `IDeckLinkIterator`, then walk `Next()` reading `GetModelName` / `GetSerialNumber`.
//!
//! Without the feature, `enumerate()` returns an explanatory error so the skeleton still
//! links and CI stays green. The returned pairs are merged into the discovered devices by
//! index in `main.rs`, overriding the placeholder `filesystem-probe` model / empty serial.

#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals)]

#[cfg(feature = "decklink")]
mod imp {
    use libloading::{Library, Symbol};
    use std::ffi::{CStr, OsStr};
    use std::os::raw::c_char;

    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

    // HRESULT S_OK
    const S_OK: i32 = 0;

    type CreateIter = unsafe extern "C" fn(*mut *mut IDeckLinkIterator) -> i32;

    /// Returns `(model, serial)` pairs in `IDeckLinkIterator` order.
    pub fn enumerate() -> Result<Vec<(String, String)>, String> {
        let lib = unsafe { Library::new(OsStr::new("libDeckLinkAPI.so")) }
            .map_err(|e| format!("load libDeckLinkAPI.so failed: {e}"))?;

        let create: Symbol<CreateIter> = unsafe {
            lib.get(b"CreateDeckLinkIteratorInstance_0004\0")
                .map_err(|e| format!("symbol CreateDeckLinkIteratorInstance_0004 not found: {e}"))?
        };

        let mut iter: *mut IDeckLinkIterator = std::ptr::null_mut();
        let hr = unsafe { create(&mut iter) };
        if hr != S_OK || iter.is_null() {
            return Err(format!("CreateDeckLinkIteratorInstance_0004 failed hr={hr}"));
        }

        let vtbl = unsafe { (*iter).lpVtbl };
        let next = unsafe { (*vtbl).Next }.ok_or("IDeckLinkIterator::Next missing from vtable")?;
        let release_iter =
            unsafe { (*vtbl).Release }.ok_or("IDeckLinkIterator::Release missing from vtable")?;

        let mut out = Vec::new();
        loop {
            let mut decklink: *mut IDeckLink = std::ptr::null_mut();
            let hr = unsafe { next(iter, &mut decklink) };
            if hr != S_OK || decklink.is_null() {
                break;
            }
            let dv = unsafe { (*decklink).lpVtbl };
            let get_model =
                unsafe { (*dv).GetModelName }.ok_or("IDeckLink::GetModelName missing from vtable")?;
            let get_serial = unsafe { (*dv).GetSerialNumber }
                .ok_or("IDeckLink::GetSerialNumber missing from vtable")?;
            let release_dev =
                unsafe { (*dv).Release }.ok_or("IDeckLink::Release missing from vtable")?;

            let mut model_ptr: *mut c_char = std::ptr::null_mut();
            let mut serial_ptr: *mut c_char = std::ptr::null_mut();
            unsafe {
                let _ = get_model(decklink, &mut model_ptr);
                let _ = get_serial(decklink, &mut serial_ptr);
            }
            let model = unsafe { read_cstr(model_ptr) };
            let serial = unsafe { read_cstr(serial_ptr) };
            out.push((model, serial));

            // Release the per-device interface (iterator keeps its own ref).
            unsafe {
                let _ = release_dev(decklink);
            }
        }

        unsafe {
            let _ = release_iter(iter);
        }
        Ok(out)
    }

    /// Read a DeckLink-returned `char*` (nullable). The SDK allocates these via its own
    /// string allocator; a production build must call `ReleaseString` to free. For smoke
    /// enumeration we only read (minor one-shot leak at startup is acceptable).
    unsafe fn read_cstr(p: *mut c_char) -> String {
        if p.is_null() {
            String::new()
        } else {
            CStr::from_ptr(p as *const c_char)
                .to_string_lossy()
                .into_owned()
        }
    }
}

#[cfg(not(feature = "decklink"))]
mod imp {
    pub fn enumerate() -> Result<Vec<(String, String)>, String> {
        Err(
            "decklink feature not compiled in — rebuild with `--features decklink` and \
             DECKLINK_SDK_INCLUDE=<SDK Linux/include> (requires libclang)"
                .into(),
        )
    }
}

pub use imp::enumerate;
