//! Gate 6/7 — real DeckLink device enumeration via bindgen-generated FFI.
//!
//! With the `bmd` feature compiled in, `bindings.rs` (generated by `build.rs` from
//! `DeckLinkAPI.h`) provides the COM vtable structs. We dlopen `libDeckLinkAPI.so`
//! (validated by Gate 2.5), call `CreateDeckLinkIteratorInstance_0004` to obtain an
//! `IDeckLinkIterator`, then walk `Next()` reading `GetModelName` / `GetSerialNumber`.
//!
//! `hardware-test` adds a verbose Device Registry (model/serial/status) for BMD.
//!
//! Without the feature, `enumerate()` returns an explanatory error so the skeleton
//! still links and CI stays green.

#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals)]

#[cfg(feature = "bmd")]
mod imp {
    use libloading::{Library, Symbol};
    use std::ffi::{CStr, OsStr};
    use std::os::raw::c_char;

    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

    // HRESULT S_OK
    const S_OK: i32 = 0;

    type CreateIter = unsafe extern "C" fn(*mut *mut IDeckLinkIterator) -> i32;

    /// Walk IDeckLinkIterator::Next, returning (model, serial) pairs in order.
    fn iter_devices() -> Result<Vec<(String, String)>, String> {
        let lib = unsafe { Library::new(OsStr::new("libDeckLinkAPI.so")) }
            .map_err(|e| format!("load libDeckLinkAPI.so failed: {e}"))?;

        let create: Symbol<CreateIter> = unsafe {
            lib.get(b"CreateDeckLinkIteratorInstance_0004\0")
                .map_err(|e| format!("symbol CreateDeckLinkIteratorInstance_0004 not found: {e}"))?
        };

        let mut iter: *mut IDeckLinkIterator = std::ptr::null_mut();
        let hr = unsafe { create(&mut iter) };
        if hr != S_OK || iter.is_null() {
            return Err(format!("CreateDeckLinkIteratorInstance_0004 failed hr={hr}"));
        }

        // bindgen emits the COM vtable as the first struct field; the field name is
        // `__bindgen_vtable` (the pointer type is `<Iface>__bindgen_vtable`).
        let vtbl = unsafe { (*iter).__bindgen_vtable };
        let next = unsafe { (*vtbl).Next }.ok_or("IDeckLinkIterator::Next missing from vtable")?;
        let release_iter =
            unsafe { (*vtbl).Release }.ok_or("IDeckLinkIterator::Release missing from vtable")?;

        let mut out = Vec::new();
        loop {
            let mut decklink: *mut IDeckLink = std::ptr::null_mut();
            let hr = unsafe { next(iter, &mut decklink) };
            if hr != S_OK || decklink.is_null() {
                break;
            }
            let dv = unsafe { (*decklink).__bindgen_vtable };
            let get_model =
                unsafe { (*dv).GetModelName }.ok_or("IDeckLink::GetModelName missing from vtable")?;
            let get_serial = unsafe { (*dv).GetSerialNumber }
                .ok_or("IDeckLink::GetSerialNumber missing from vtable")?;
            let release_dev =
                unsafe { (*dv).Release }.ok_or("IDeckLink::Release missing from vtable")?;

            let mut model_ptr: *mut c_char = std::ptr::null_mut();
            let mut serial_ptr: *mut c_char = std::ptr::null_mut();
            unsafe {
                let _ = get_model(decklink, &mut model_ptr);
                let _ = get_serial(decklink, &mut serial_ptr);
            }
            let model = unsafe { read_cstr(model_ptr) };
            let serial = unsafe { read_cstr(serial_ptr) };
            out.push((model, serial));

            unsafe {
                let _ = release_dev(decklink);
            }
        }

        unsafe {
            let _ = release_iter(iter);
        }
        Ok(out)
    }

    /// Read a DeckLink-returned `char*` (nullable). The SDK allocates via its own string
    /// allocator; a production build must `ReleaseString` to free. For enumeration we only
    /// read (minor one-shot startup leak acceptable).
    unsafe fn read_cstr(p: *mut c_char) -> String {
        if p.is_null() {
            String::new()
        } else {
            CStr::from_ptr(p as *const c_char)
                .to_string_lossy()
                .into_owned()
        }
    }

    pub fn enumerate() -> Result<Vec<(String, String)>, String> {
        iter_devices()
    }

    /// Build a human-readable "DeckLink Device Registry" table (Gate 7 target output).
    pub fn registry() -> Result<String, String> {
        let devs = iter_devices()?;
        let mut s = String::from("DeckLink Device Registry\n────────────────────────\n");
        for (i, (model, serial)) in devs.iter().enumerate() {
            s.push_str(&format!(
                "ID: {i}\nModel: {model}\nSerial: {serial}\nStatus: AVAILABLE\n\n"
            ));
        }
        Ok(s)
    }
}

#[cfg(not(feature = "bmd"))]
mod imp {
    pub fn enumerate() -> Result<Vec<(String, String)>, String> {
        Err(
            "bmd feature not compiled in — rebuild with `--features bmd` and \
             DECKLINK_SDK_INCLUDE=<SDK Linux/include> (requires libclang)"
                .into(),
        )
    }
}

#[cfg(feature = "bmd")]
pub use imp::{enumerate, registry};
#[cfg(not(feature = "bmd"))]
pub use imp::enumerate;
